INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (13, '电脑办公', '组装电脑主机台式i5八核9高配i7办公游戏家用整机', '常州威登电子设备有限公司', 3500, 195, '002.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (14, '电脑办公', 'i7级八核游戏型电竞独显16G台式机LOL组装电脑', '常州威登电子设备有限公司', 3799, -2, '003.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (15, '电脑办公', '酷睿i5四核/16G/GTX1060独显台式机组装电脑', '常州威登电子设备有限公司', 8799, 199, '004.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (16, '电脑办公', '酷睿i5四核/16G/GTX1060独显台式机组装电脑', '常州威登电子设备有限公司', 2899, 480, '005.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (17, '电脑办公', '酷睿I7 9700/GTX1060高配台式电脑主机', '常州威登电子设备有限公司', 2500, 498, '006.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (19, '电脑办公', '女生款学生办公用商务游戏本手提电脑全金属高配畅玩', '东莞市思瑞电子设备有限公司', 2600, 500, '007.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (20, '电脑办公', 'Lenovo/联想 小新15 -i7笔记本电脑', '东莞市思瑞电子设备有限公司', 2700, 400, '008.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (21, '电脑办公', '酷睿I5 10400F/10600KF/GTX1060游戏电竞独显台式机', '东莞市思瑞电子设备有限公司', 3299, 200, '008.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (22, '手机数码', 'Mate40pro至尊版12+512G大内存全新官方旗舰正品5G', '东莞市思瑞电子设备有限公司', 2800, 500, '009.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (23, '手机数码', '新款千元学生价游戏5G网络全网通手机大屏智能超薄', '常州市振创电子设备有限公司\r\n', 3000, 500, '010.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (24, '手机数码', '【12期分期】OPPO A93 oppoa93手机5g新款上市', '常州市振创电子设备有限公司\r\n', 3799, 500, '011.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (25, '手机数码', '[最后4小时24期免息+赠耳机]meizu魅族18 Pro骁龙888', '常州市振创电子设备有限公司\r\n', 8799, 400, '012.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (26, '手机数码', 'vivo iQOO Neo5 5g手机 iqooneo5 ipooneo5 ', '常州市振创电子设备有限公司\r\n', 2899, 200, '013.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (27, '手机数码', 'meizu魅族18骁龙888防抖5G手机2K屏幕小屏满血旗舰零广告拍照', '常州远甬网印设备有限公司', 2500, 500, '014.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (28, '手机数码', ' 红米/Redmi K40 Pro 5G手机官方旗舰店正品全网通系列新款', '常州远甬网印设备有限公司', 2600, 500, '015.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (29, '手机数码', 'meizu魅族18骁龙888防抖5G手机2K屏幕小屏满血旗舰零广告拍照', '常州远甬网印设备有限公司', 2700, 500, '016.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (30, '蓝牙音箱', '科达广场舞音响大屏跳舞拉杆视频音响户外大功率无线话筒家用', '常州远甬网印设备有限公司', 3299, 400, '017.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (32, '蓝牙音箱', '曼龙户外音响高端大功率唱歌移动拉杆带声卡内录直播网红乐器音响', '广州晨讯电子设备有限公司\r\n', 2800, 200, '019.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (33, '蓝牙音箱', '音响带显示屏幕大屏无线话筒拉杆户外家用k歌蓝牙唱歌跳舞', '广州晨讯电子设备有限公司\r\n', 3000, 500, '020.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (34, '蓝牙音箱', '高端户外广场舞音响吉他音箱曼龙M-08霹雳舞大叔户外专用表演音箱', '广州晨讯电子设备有限公司\r\n', 3799, 500, '021.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (35, '蓝牙音箱', 'KKH K6家庭ktv音响套装点歌一体机专业音箱功放全套K歌家用卡拉ok', '广州晨讯电子设备有限公司\r\n', 8799, 500, '022.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (36, '蓝牙音箱', '金正广场舞音响音箱户外唱歌拉杆移动跳舞k歌蓝牙大音量大功率', '上海源捷电子设备有限公司', 2899, 400, '023.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (37, '蓝牙音箱', '联想 户外演出移动拉杆音响跳广场舞音箱带无线话筒K歌便携式', '上海源捷电子设备有限公司', 2500, 200, '034.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (38, '蓝牙耳机', '原装正品有线耳机适用华为p20p30p40手机type-c荣耀', '上海源捷电子设备有限公司', 2600, 499, '025.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (39, '蓝牙耳机', '电脑耳机头戴式耳麦电竞游戏台式笔记本有线吃鸡听声辩位带麦克风', '上海源捷电子设备有限公司', 2700, 500, '026.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (40, '蓝牙耳机', '真无线蓝牙耳机双耳运动入耳式迷你隐形超长待机微小型高端', '上海源捷电子设备有限公司', 3299, 500, '027.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (41, '蓝牙耳机', '兰士顿耳机有线高音质适用于苹果vivo华为oppo小米手机typec', '上海源捷电子设备有限公司', 2800, 400, '028.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (42, '蓝牙耳机', '原装正品耳机适用vivo通用x9x21vivox23vivox20x7x27plus原配', '上海源捷电子设备有限公司', 3000, 200, '029.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (43, '蓝牙耳机', '原装正品耳机适用华为耳机type-c入耳式p20p30pro p40mate20', '东莞市万江广源变频电子设备厂\r\n', 3799, 500, '030.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (44, '蓝牙耳机', 'huawei华为蓝牙耳机不入耳骨传导久戴不痛无线挂耳式运动开车专用', '东莞市万江广源变频电子设备厂\r\n', 8799, 500, '031.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (48, '电脑办公', 'Lenovo/联想AIO逸 23.8英寸网课电脑 台式电脑一体机 ', '常州威登电子设备有限公司', 4599, 500, '034.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (49, '电脑办公', '新创云迷你便携口袋主机赛扬四核N4100家用办公客厅4K', '常州威登电子设备有限公司', 3499, 500, '035.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (50, '电脑办公', 'Apple苹果一体机电脑21.5寸27英寸 imac设计游戏家用办公台式机 ', '常州威登电子设备有限公司', 3599, 500, '036.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (51, '电脑办公', 'Lenovo/联想台式电脑天逸510s四核高配办公整机主机全套原装官方旗舰店', '常州威登电子设备有限公司', 3299, 500, '037.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (52, '电脑办公', 'Dell戴尔Vostro成就3671/3881十代i3/i5品牌台式机电脑高配主机游戏办公', '常州威登电子设备有限公司', 2699, 500, '038.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (53, '电脑办公', 'Dell/戴尔 XPS 8940 11代英特尔酷睿i7台式机3070设计师电脑游戏电竞主机', '常州威登电子设备有限公司', 6799, 500, '039.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (54, '电脑办公', '华硕电脑主机十代i5 10400F/10600KF/GTX1650/1660全家桶吃鸡游戏', '常州威登电子设备有限公司', 5249, 500, '040.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (55, '电脑办公', '酷睿i7八核高配组装台式电脑主机全套 24英寸曲面显示器吃鸡DNF', '常州威登电子设备有限公司', 1050, 500, '041.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (56, '电脑办公', '【升级5年上门】惠普HP 十代酷睿i3/i5/i7迷你主机商用台式电脑', '常州威登电子设备有限公司', 2699, 500, '042.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (57, '手机数码', 'Mate40正品12+256G骁龙865学生价游戏智能手机全网通适用于华为', '东莞市思瑞电子设备有限公司', 2600, 500, '043.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (58, '手机数码', '3期免息/当天发货】Xiaomi/小米 红米 Redmi K40 5G手机官方旗舰店红米k40', '东莞市思瑞电子设备有限公司', 2700, 500, '044.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (59, '手机数码', '【顺丰当天发+送33W充电套装】Xiaomi/小米 小米11青春版 ', '东莞市思瑞电子设备有限公司', 3299, 500, '045.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (60, '手机数码', 'yivi X11正品5G学生价百元水滴全面屏安卓指纹游戏全网通智能手机 ', '东莞市思瑞电子设备有限公司', 2800, 200, '090.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (61, '手机数码', '闲鱼优品苹果iPhoneX国行xr官换xsmax未激活手机', '东莞市思瑞电子设备有限公司', 3000, 500, '046.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (62, '手机数码', '华为 全新原封正品 （华为售后全国联保一年）Huawei', '东莞市思瑞电子设备有限公司', 3799, 500, '091.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (63, '手机数码', 'Huawei/华为Mate20RS保时捷设计手机Mate20', '东莞市思瑞电子设备有限公司', 8799, 500, '047.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (64, '手机数码', '【新配色立减900元】iPhone 12 5G手机苹果', '东莞市思瑞电子设备有限公司', 996, 500, '048.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (65, '手机数码', '官网HUAWEI 华为畅享10 plus直降千元手机', '东莞市思瑞电子设备有限公司', 3199, 500, '049.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (66, '手机数码', '【24期免息+选无线充】Xiaomi/小米 小米10S 5G手机骁龙870', '东莞市思瑞电子设备有限公司', 4599, 500, '050.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (67, '手机数码', '（华为售后全国联保一年）【华为原装正品 顺丰包邮 Huawei/华为 ', '东莞市思瑞电子设备有限公司', 3499, 500, '051.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (68, '手机数码', '2020新品Apple/苹果 iPhone 12 Pro Max苹果12Pro Max手机6.7英寸 ', '东莞市思瑞电子设备有限公司', 3599, 500, '052.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (69, '手机数码', '【OPPO A32】全网通手机128G大内存四摄5000mAh超大电池18W', '东莞市思瑞电子设备有限公司', 3299, 500, '053.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (70, '蓝牙音箱', 'Divoom点音 玛奇朵迷你无线蓝牙音箱小型随身便携式手机音响可爱 ', '广州晨讯电子设备有限公司\r\n', 2699, 500, '054.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (71, '蓝牙音箱', '蓝悦无线蓝牙音箱大音量手机迷你便携式随身户外小型钢炮', '广州晨讯电子设备有限公司\r\n', 6799, 500, '055.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (72, '蓝牙音箱', 'DEVIALET Phantom帝瓦雷重低音无线蓝牙音响大功率发烧HiFi音箱 ', '广州晨讯电子设备有限公司\r\n', 5249, 500, '056.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (73, '蓝牙音箱', 'JBL BOOMBOX蓝牙音箱音响小型户外便携式美国音乐战神超重低音炮 ', '广州晨讯电子设备有限公司\r\n', 1050, 200, '057.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (74, '蓝牙音箱', 'HP/惠普蓝牙音箱低音炮小便携式双喇叭3d环绕立体声随身户外运动防水', '广州晨讯电子设备有限公司\r\n', 2699, 500, '058.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (75, '蓝牙音箱', 'JBL BOOMBOX2代音乐战神二代无线蓝牙音箱户外便携音响重低音防水 ', '广州晨讯电子设备有限公司\r\n', 2600, 500, '059.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (76, '蓝牙音箱', '无线蓝牙音箱内置人工智能AI助手语音控制手机外放插卡迷你小音响', '广州晨讯电子设备有限公司\r\n', 2700, 500, '060.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (77, '蓝牙音箱', '无线蓝牙音箱手机重低音炮双喇叭防水便携户外运动插卡迷你小音响 ', '广州晨讯电子设备有限公司\r\n', 3299, 500, '061.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (78, '蓝牙音箱', '【官方正品】AKG/爱科技 S20便携无线蓝牙音箱防水超重低音炮', '广州晨讯电子设备有限公司\r\n', 2800, 500, '062.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (79, '蓝牙音箱', '哈曼卡顿琉璃三代音箱AURA STUDIO 3代家用电脑无线蓝牙音响低音2 ', '广州晨讯电子设备有限公司\r\n', 3000, 500, '063.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (80, '蓝牙音箱', '汇祥29寸高清视频广场舞音响k歌拉杆音箱大功率无线话筒户外35寸', '广州晨讯电子设备有限公司\r\n', 3799, 500, '064.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (81, '蓝牙音箱', '跳广场舞音响带显示屏幕康佳新款大屏便携式移动小音响户外', '广州晨讯电子设备有限公司\r\n', 8799, 500, '065.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (82, '蓝牙音箱', '科凌无线蓝牙音箱户外跑步运动骑行便携式迷你插卡小型音响大音量', '广州晨讯电子设备有限公司\r\n', 996, 500, '066.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (83, '蓝牙耳机', 'EDIFIER/漫步者 lollipods pro主动降噪蓝牙耳机真无线入耳式运动 ', '广州晨讯电子设备有限公司\r\n', 3199, 500, '067.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (84, '蓝牙耳机', 'QCY T8无线蓝牙耳机双耳半入耳式运动跑步车载通话通用超长续航 ', '上海源捷电子设备有限公司', 4599, 500, '068.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (85, '蓝牙耳机', '无线蓝牙耳机可爱女生款双耳迷你入耳式跑步运动弹窗苹果安卓通用 ', '上海源捷电子设备有限公司', 3499, 500, '069.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (86, '蓝牙耳机', '漫步者VO6真无线蓝牙耳机双耳半入耳式降噪运动跑步超长待机续航', '上海源捷电子设备有限公司', 3599, 200, '070.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (87, '蓝牙耳机', 'Huawei华为无线不入耳骨传导蓝牙耳机双耳久戴不痛运动跑步', '上海源捷电子设备有限公司', 3299, 500, '071.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (88, '蓝牙耳机', '蓝牙耳机无线适用于苹果华为华强北四代4代真大电量高音质pro', '上海源捷电子设备有限公司', 2699, 500, '072.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (89, '蓝牙耳机', '【赠耳机包】Sony/索尼 WI-C200 无线蓝牙耳机双耳挂脖式运动跑步', '上海源捷电子设备有限公司', 6799, 500, '073.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (90, '蓝牙耳机', '联想蓝牙耳机真无线2021年新款双耳运动跑步小型隐形无延迟超长待机', '上海源捷电子设备有限公司', 5249, 500, '074.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (91, '蓝牙耳机', '无线蓝牙耳机超长待机商务运动适用小米oppo华为vivo安卓苹果iPhone', '上海源捷电子设备有限公司', 1050, 500, '075.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (92, '蓝牙耳机', '【官方正品】华为Freebuds 3i无线蓝牙耳机主动降噪跑步运动耳机', '上海源捷电子设备有限公司', 2699, 500, '076.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (93, '蓝牙耳机', '原裝正品无线蓝牙耳机运动入耳式适用huawei华为降噪游戏无延迟', '上海源捷电子设备有限公司', 2600, 500, '077.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (94, '蓝牙耳机', 'Iriver/艾利和 AK T8iE MkII二代特斯拉单元入耳机T9iE圆声带行货 ', '上海源捷电子设备有限公司', 2700, 500, '078.jpg');
INSERT INTO `products` (`id`, `type`, `name`, `company`, `price`, `number`, `picture`) VALUES (95, '蓝牙耳机', '隐形入耳蓝牙耳机 微小型单耳迷你无线耳塞式超小微型肉色非最小 ', '上海源捷电子设备有限公司', 3299, 500, '079.jpg');
